title: Fauza Annisa
logo: /img-assets/Photo-ID.jpeg
theme: jekyll-theme-minimal
description: A Data Science graduate with over 3 years of experience in data analytics within the e-commerce industry, concentrating on data analysis, data visualization, and market research.
