title: Fauza Annisa
description: A Data Science graduate with over 3 years of experience in data analytics within the e-commerce industry, concentrating on data analysis, data visualization, and market research.
theme: minimal
